[package]
name = "prototype_excel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.6"
calamine = "0.22.1"
memory-stats = "1.1.0"
